application: mvmtecnologia
version: 1
runtime: python
api_version: 1
threadsafe:  true


default_expiration: "5d"

handlers:
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /img
  static_dir: img

- url: /.* 
  script: controller.py


