application: mvmtecnologia
version: 1
runtime:  python27
api_version: 1
threadsafe:  true


default_expiration: "1d"

handlers:
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /img
  static_dir: img

- url: /sitemap.xml
  static_files: sitemap.xml
  upload: sitemap.xml
  
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /.*
  script: controller.application

